apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vcc-eksctl
  region: eu-west-2

managedNodeGroups:
  - name: nodegroup1
    instanceType: t3.large
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key


